# Generated by Django 2.2.3 on 2019-07-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('body', models.TextField(blank=True, verbose_name='내용')),
                ('tags', models.CharField(max_length=50, verbose_name='태그')),
                ('publishedDate', models.DateField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
